### PR TITLE
Fix portability issues

### LINKED ISSUE #34: [Bug] u_int_* is implementation specific and should never be used
`sys/types.h` and its `u_int_*`  should never be used.
`stdint.h` and its `uint_*` is the C99 standard.

### PR DESCRIPTION
**Pull request by albap**
sys/cdefs.h is an internal glibc header and should *never* be used
u_int_* is system dependent, the C99 standard is uint_*

fixes #34

### CODE REVIEW

File: rem_pio2/cdefs-compat.h [hunk 1]
```diff
@@ -1,25 +1,10 @@
...
-#if defined(__cplusplus)
-#define	__BEGIN_DECLS	extern "C" {
-#define	__END_DECLS	}
-#else
-#define	__BEGIN_DECLS
-#define	__END_DECLS
-#endif
-
+#if defined(_WIN32) || defined(__sun)
 #define _SYS_CDEFS_H_
```
Comment (tkelman) [inline rem_pio2/cdefs-compat.h]: I don't even think we would need this guard if we're not defining anything else? @yuyichao what do you think?

Comment (yuyichao) [inline rem_pio2/cdefs-compat.h]: This define should be removed as well.

**Comment by albap** [comment]
> All checks have failed

What's this about?

**Comment by yuyichao** [comment]
Looks like someone enabled travis without adding a config file?

**Comment by albap** [comment]
Can you merge the commit? Doesn't look like there's anything wrong.

**Comment by yuyichao** [comment]
LGTM. Could use a [squash](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit).

**Comment by albap** [comment]
squashed!

**Comment by yuyichao** [comment]
LGTM, will merge tomorrow if no one else has any comment.

**Comment by yuyichao** [comment]
Hmm? the unsquashed commits are added back?

**Comment by albap** [comment]
Fixed again, sorry.
Looks good? I won't touch this anymore :)

**Comment by yuyichao** [comment]
Yes. Looks good again now.
